name = "adao/multisig_drep"
version = "0.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = ""

[[dependencies]]
name = "aiken-lang/stdlib"
version = "48f0fa6947abbc6053f1af53cc63a808681095b2"
source = "github"
