name = "adao/multisig_drep"
version = "0.0.0"
# compiler = "v1.1.0"
compiler = "v1.1.3"
plutus = "v3"
license = "Apache-2.0"
description = ""

[[dependencies]]
name = "aiken-lang/stdlib"
version = "25d9f1d63041a5574dce18632d7477ce7ff26665"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "f2670924f23904553bc8e80ba6788ef8d19eb844"
source = "github"
